name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.14.0)'
        required: true
      title:
        description: 'Release title'
        required: false
      body:
        description: 'Release description / changelog'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.title || github.event.inputs.tag }}
          body: |
            Documentation updates for [Container Storage Modules 1.13.0](https://github.com/dell/csm/releases/tag/v1.13.0)

            - [CSM for Authorization](https://github.com/dell/karavi-authorization/releases/tag/v1.13.0)  
            - [CSM for Replication](https://github.com/dell/csm-replication/releases/tag/v1.11.0)  
            - [CSM for Observability](https://github.com/dell/karavi-observability/releases/tag/v1.11.0)  
            - [CSM for Resiliency](https://github.com/dell/karavi-resiliency/releases/tag/v1.12.0)  
            - [CSI Driver for Dell PowerFlex](https://github.com/dell/csi-powerflex/releases/tag/v2.13.0)  
            - [CSI Driver for Dell PowerMax](https://github.com/dell/csi-powermax/releases/tag/v2.13.0)  
            - [CSI Driver for Dell PowerScale](https://github.com/dell/csi-powerscale/releases/tag/v2.13.0)  
            - [CSI Driver for Dell PowerStore](https://github.com/dell/csi-powerstore/releases/tag/v2.13.0)  
            - [CSI Driver for Dell Unity](https://github.com/dell/csi-unity/releases/tag/v2.13.0)  
            - [CSM Installation Wizard](https://dell.github.io/csm-docs/docs/deployment/csminstallationwizard/src/)  
            - [Tool to validate Dell CSI Drivers](https://github.com/dell/cert-csi/releases/tag/v1.7.0)  
            - [CSM Operator](https://github.com/dell/csm-operator/releases/tag/v1.8.0)

          draft: false
          draft: TRUE
          prerelease: false